### ISSUE TITLE
[IDEA] Address interfaces by MAC-address instead of interface name.

### ISSUE THREAD

**Issue by sndrsmnk** [ypconfig/ypconfig#2]
I would like to address interfaces by MAC-address rather than interface names, which aren't stable.

Perhaps like:
```
901b0ec6c476:
  ifname: eth0
  mac: 90:1b:0e:c6:c4:76
  adminstate: UP
  mtu: 1500
```
Or i would be fine if specifying 'mac: xyz' to an interface called 'eth0' makes ypconfig bail if that combination of ifname/macaddr wasn't found. Which is probably much easier to implement.

I'm not entirely sure about the preferred way to specify it.

I just want to make sure that the interface i call 'eth0' is actually the interface that i expect to be 'eth0'.
